name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.11]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyside6 pyinstaller "numpy<2.0.0" scipy matplotlib

    - name: Install platform-specific dependencies (Linux)
      if: runner.os == 'Linux'
      run: sudo apt-get install -y libxcb-xinerama0

    - name: Install platform-specific dependencies (macOS)
      if: runner.os == 'macos'
      run: |
        brew install libomp

    - name: Build the application with PyInstaller
      run: |
        pyinstaller --onefile main.py

    - name: Archive the build
      run: |
        mkdir release
        mv dist/* release/

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ runner.os }}
        path: release/*

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download build artifacts from all platforms
      uses: actions/download-artifact@v4
      with:
        name: build-Windows
        path: ./release/Windows

    - name: Download build artifacts from macOS
      uses: actions/download-artifact@v4
      with:
        name: build-macOS
        path: ./release/macOS

    - name: Download build artifacts from Linux
      uses: actions/download-artifact@v4
      with:
        name: build-Linux
        path: ./release/Linux

    - name: Install GitHub CLI and Set auth
      run: |
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /usr/share/keyrings/githubcli-archive-keyring.gpg > /dev/null
        sudo apt update
        sudo apt install gh
        gh auth refresh -s workflow

    - name: Debug file paths
      run: |
        echo "Files to be uploaded:"
        find ./release/Windows -type f
        find ./release/macOS -type f
        find ./release/Linux -type f

    - name: Create and upload GitHub Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Initialize an empty array to hold the file paths
        files=()

        # Add all files from the Windows, macOS, and Linux directories to the array
        files+=($(find ./release/Windows -type f))
        files+=($(find ./release/macOS -type f))
        files+=($(find ./release/Linux -type f))

        # Print the files to be uploaded for debugging purposes
        echo "Files to be uploaded: $files[@]"

        # Upload the files to GitHub Release
        gh release create "v${{ github.run_number }}" "${files[@]}" --title "Release v${{ github.run_number }}" --notes "Automated release generated by GitHub Actions."
